# Generated by Django 6.1 on 2026-08-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='view_module', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Conceito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descricao', models.TextField()),
                ('explicacao', models.TextField(help_text='Explicação detalhada do conceito')),
                ('exemplo_codigo', models.TextField(blank=True, help_text='Exemplo em Python/NumPy')),
                ('icone', models.CharField(default='widgets', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos', to='concepts.modulo')),
            ],
            options={
                'ordering': ['modulo__ordem', 'ordem'],
            },
        ),
    ]
