# Generated by Django 6.1 on 2026-08-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceito',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='conceito',
            name='updated_at',
        ),
    ]
